version: '3'

services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"

  backend:
    build: ./Backend
    ports:
      - "8070:8070"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db_student

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo-data:
