version: '3'

services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    user: "myuser:mygroup"

  backend:
    build: ./Backend
    ports:
      - "8070:8070"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/db_student
    depends_on:
      - mongo
    user: "myuser:mygroup"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
